version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./build/db.Dockerfile
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - db_nw
    restart: unless-stopped
  webapp:
    build:
      context: .
      dockerfile: ./build/web.Dockerfile
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/treederboards
      - APP_MODULE=app.app:app
    networks:
      - db_nw
    depends_on:
      - db
    restart: unless-stopped
networks:
  db_nw:
    driver: bridge
volumes:
  dbdata:
