version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./build/db.Dockerfile
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - db_nw
    restart: unless-stopped
  webapp:
    build:
      context: .
      dockerfile: ./build/web-dev.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/treederboards
      - APP_MODULE=app.main:app
      - SERVER_TYPE=development
      - PORT=8000
      - MAX_WORKERS=1
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - db_nw
    depends_on:
      - db
    restart: unless-stopped
    command: /start-reload.sh
    volumes:
      - "./app:/app/app"
networks:
  db_nw:
    driver: bridge
volumes:
  dbdata:
